### ISSUE TITLE
Accepting PR?

### ISSUE THREAD

**Issue by mathesouza** [rlivings39/vscode-fzf-quick-open#1]
Hello, thanks for the extension.
We have some ideas to improve the workflow using the extension, just like the CTRL+P works.
I want to know if you are accepting PR or should we fork it and work in another rep?

Thanks!

About the ideas:

- Add  ```&& exit``` at the end of the command, so you dont have to close de terminal manually after opening a file.
- Add filtering to the command, like search only git files.

I'm thinking in a lot of features xD

**Comment by rlivings39** [comment]
PRs greatly appreciated!

Some initial thoughts on the ideas:

* I'd advocate for the `&& exit` to be user configurable. In many cases I find it useful to have the terminal remain open as I sometimes tweak the `fzf` command. That also saves on the startup expense of launching a terminal panel.

* Limiting to git sounds reasonable. I'd also want a way to search everything. Limiting to git-tracked files is the default behavior when using `fd` instead of `find with `fzf`. Have you checked that out? With that setup running `fzf` will only show files tracked by git.

Some background on my use case is that I often work with pretty large repos. To support that, we tend to have a restricted git repo to keep `git status` fast enough to be tolerable. However, I may want to find and read files that are not tracked by git in my local repo.

**Comment by mathesouza** [comment]
Agree about the exit being user configuration.
About the fd i'll check it out.

I'll study the changes, thanks bro.

**Comment by rlivings39** [comment]
@mathesouza are you planning to add in the auto close? If not I could pop it in this weekend.

**Comment by mathesouza** [comment]
@rlivings39 sorry, i've been working in other repositories, you can go on.
A friend of mine made something similar.
You can check it out; https://github.com/tatosjb/vscode-fuzzy-search
